name: Upload Python package to Test PyPI
on:
  push:
    branches:
    - master
  # release:
  #   types: # This configuration does not affect the page_build event above
  #     - created

jobs:
  deploy-test-pypi:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[dev]
    - name: Create package
      run: python setup.py sdist bdist_wheel --universal
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
